rename 's/\.\d+.+_genomic//' genomes/aactinomycetemcomitans/*.gz
rename 's/\.\d+.+_genomic//' genomes/aphagocytophilum/*.gz
rename 's/\.\d+.+_genomic//' genomes/bbacilliformis/*.gz
rename 's/\.\d+.+_genomic//' genomes/bcepacia_complex/*.gz
rename 's/\.\d+.+_genomic//' genomes/bcereus/*.gz
rename 's/\.\d+.+_genomic//' genomes/bhampsonii/*.gz
rename 's/\.\d+.+_genomic//' genomes/bhenselae/*.gz
rename 's/\.\d+.+_genomic//' genomes/bhyodysenteriae/*.gz
rename 's/\.\d+.+_genomic//' genomes/blicheniformis/*.gz
rename 's/\.\d+.+_genomic//' genomes/bpilosicoli/*.gz
rename 's/\.\d+.+_genomic//' genomes/bpseudomallei/*.gz
rename 's/\.\d+.+_genomic//' genomes/bsubtilis/*.gz
rename 's/\.\d+.+_genomic//' genomes/cbotulinum/*.gz
rename 's/\.\d+.+_genomic//' genomes/cconcisuscurvus/*.gz
rename 's/\.\d+.+_genomic//' genomes/cdifficile/*.gz
rename 's/\.\d+.+_genomic//' genomes/cdiphtheriae/*.gz
rename 's/\.\d+.+_genomic//' genomes/cfetus/*.gz
rename 's/\.\d+.+_genomic//' genomes/cfreundii/*.gz
rename 's/\.\d+.+_genomic//' genomes/chelveticus/*.gz
rename 's/\.\d+.+_genomic//' genomes/chyointestinalis/*.gz
rename 's/\.\d+.+_genomic//' genomes/cinsulaenigrae/*.gz
rename 's/\.\d+.+_genomic//' genomes/cjejuni/*.gz
rename 's/\.\d+.+_genomic//' genomes/clanienae/*.gz
rename 's/\.\d+.+_genomic//' genomes/clari/*.gz
rename 's/\.\d+.+_genomic//' genomes/cmaltaromaticum/*.gz
rename 's/\.\d+.+_genomic//' genomes/cperfringens/*.gz
rename 's/\.\d+.+_genomic//' genomes/csputorum/*.gz
rename 's/\.\d+.+_genomic//' genomes/cupsaliensis/*.gz
rename 's/\.\d+.+_genomic//' genomes/dnodosus/*.gz
rename 's/\.\d+.+_genomic//' genomes/ecloacae/*.gz
rename 's/\.\d+.+_genomic//' genomes/efaecalis/*.gz
rename 's/\.\d+.+_genomic//' genomes/fpsychrophilum/*.gz
rename 's/\.\d+.+_genomic//' genomes/gparasuis/*.gz
rename 's/\.\d+.+_genomic//' genomes/hcinaedi/*.gz
rename 's/\.\d+.+_genomic//' genomes/hinfluenzae/*.gz
rename 's/\.\d+.+_genomic//' genomes/hpylori/*.gz
rename 's/\.\d+.+_genomic//' genomes/hsuis/*.gz
rename 's/\.\d+.+_genomic//' genomes/kaerogenes/*.gz
rename 's/\.\d+.+_genomic//' genomes/efaecium/*.gz
rename 's/\.\d+.+_genomic//' genomes/koxytoca/*.gz
rename 's/\.\d+.+_genomic//' genomes/lsolanacearum/*.gz
rename 's/\.\d+.+_genomic//' genomes/magalactiae/*.gz
rename 's/\.\d+.+_genomic//' genomes/manserisalpingitidis/*.gz
rename 's/\.\d+.+_genomic//' genomes/mbovis/*.gz
rename 's/\.\d+.+_genomic//' genomes/mcanis/*.gz
rename 's/\.\d+.+_genomic//' genomes/mcaseolyticus/*.gz
rename 's/\.\d+.+_genomic//' genomes/mcatarrhalis/*.gz
rename 's/\.\d+.+_genomic//' genomes/mflocculare/*.gz
rename 's/\.\d+.+_genomic//' genomes/mgallisepticum#1/*.gz
rename 's/\.\d+.+_genomic//' genomes/mhaemolytica/*.gz
rename 's/\.\d+.+_genomic//' genomes/mhyopneumoniae/*.gz
rename 's/\.\d+.+_genomic//' genomes/mhyorhinis/*.gz
rename 's/\.\d+.+_genomic//' genomes/miowae/*.gz
rename 's/\.\d+.+_genomic//' genomes/mplutonius/*.gz
rename 's/\.\d+.+_genomic//' genomes/mpneumoniae/*.gz
rename 's/\.\d+.+_genomic//' genomes/msciuri/*.gz
rename 's/\.\d+.+_genomic//' genomes/msynoviae/*.gz
rename 's/\.\d+.+_genomic//' genomes/orhinotracheale/*.gz
rename 's/\.\d+.+_genomic//' genomes/otsutsugamushi/*.gz
rename 's/\.\d+.+_genomic//' genomes/pacnes/*.gz
rename 's/\.\d+.+_genomic//' genomes/pdamselae/*.gz
rename 's/\.\d+.+_genomic//' genomes/pfluorescens/*.gz
rename 's/\.\d+.+_genomic//' genomes/pgingivalis/*.gz
rename 's/\.\d+.+_genomic//' genomes/plarvae/*.gz
rename 's/\.\d+.+_genomic//' genomes/pmultocida#1/*.gz
rename 's/\.\d+.+_genomic//' genomes/ppentosaceus/*.gz
rename 's/\.\d+.+_genomic//' genomes/pputida/*.gz
rename 's/\.\d+.+_genomic//' genomes/psalmonis/*.gz
rename 's/\.\d+.+_genomic//' genomes/ranatipestifer/*.gz
rename 's/\.\d+.+_genomic//' genomes/sagalactiae/*.gz
rename 's/\.\d+.+_genomic//' genomes/sbovisequinus_complex_sbsec/*.gz
rename 's/\.\d+.+_genomic//' genomes/scanis/*.gz
rename 's/\.\d+.+_genomic//' genomes/schromogenes/*.gz
rename 's/\.\d+.+_genomic//' genomes/sdysgalactiae_equisimilis/*.gz
rename 's/\.\d+.+_genomic//' genomes/sepidermidis/*.gz
rename 's/\.\d+.+_genomic//' genomes/sgallolyticus/*.gz
rename 's/\.\d+.+_genomic//' genomes/shaemolyticus/*.gz
rename 's/\.\d+.+_genomic//' genomes/shominis/*.gz
rename 's/\.\d+.+_genomic//' genomes/smaltophilia/*.gz
rename 's/\.\d+.+_genomic//' genomes/soralis/*.gz
rename 's/\.\d+.+_genomic//' genomes/spseudintermedius/*.gz
rename 's/\.\d+.+_genomic//' genomes/ssuis/*.gz
rename 's/\.\d+.+_genomic//' genomes/suberis/*.gz
rename 's/\.\d+.+_genomic//' genomes/szooepidemicus/*.gz
rename 's/\.\d+.+_genomic//' genomes/tpallidum/*.gz
rename 's/\.\d+.+_genomic//' genomes/vcholerae/*.gz
rename 's/\.\d+.+_genomic//' genomes/vparahaemolyticus/*.gz
rename 's/\.\d+.+_genomic//' genomes/vvulnificus/*.gz
rename 's/\.\d+.+_genomic//' genomes/wolbachia/*.gz
rename 's/\.\d+.+_genomic//' genomes/xfastidiosa/*.gz
rename 's/\.\d+.+_genomic//' genomes/ypseudotuberculosis/*.gz